"""initial schema

Revision ID: 3c48826c1441
Revises: 
Create Date: 2026-02-26 18:14:32.127423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c48826c1441'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

