"""sync users table with models

Revision ID: 91574d264a66
Revises: 3c48826c1441
Create Date: 2026-02-26 19:06:18.522187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '91574d264a66'
down_revision: Union[str, None] = '3c48826c1441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The legacy employees table (and its indexes) may or may not exist,
    # depending on how the schema was created previously. In MySQL the
    # indexes are dropped automatically when the table is dropped, so we
    # only guard-drop the table itself here.
    op.execute("DROP TABLE IF EXISTS employees")
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'users', ['employee_id'], ['id'])
    op.add_column('users', sa.Column('employee_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'department')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'employee_id')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'employees', ['employee_id'], ['id'])
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('department', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=1)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=1)
    # ### end Alembic commands ###

