"""initial migration

Revision ID: ac49c0a24d5c
Revises: 
Create Date: 2026-02-26 19:26:53.759147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac49c0a24d5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'auth',
        sa.Column('id', sa.Integer(), nullable=False),
        # Use bounded lengths for MySQL VARCHARs; username is unique/indexed.
        sa.Column('username', sa.String(length=191), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('table_name', sa.String(length=255), nullable=False),
        sa.Column('table_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_auth_id'), 'auth', ['id'], unique=False)
    op.create_index(op.f('ix_auth_username'), 'auth', ['username'], unique=True)

    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        # Unique/indexed string columns limited to 191 chars for MySQL.
        sa.Column('username', sa.String(length=191), nullable=True),
        sa.Column('email', sa.String(length=191), nullable=False),
        sa.Column('employee_id', sa.String(length=191), nullable=True),
        sa.Column('full_name', sa.String(length=255), nullable=True),
        sa.Column('department', sa.String(length=255), nullable=True),
        sa.Column('role', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table(
        'attendance',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('status', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['employee_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_auth_username'), table_name='auth')
    op.drop_index(op.f('ix_auth_id'), table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###

